package secrets

import (
	clientv1 "github.com/rancher/shepherd/clients/rancher/v1"
)

// listTestType is one TestList case: a Steve secrets list request made as user, optionally scoped
// to namespace, and what the response must contain.
type listTestType struct {
	description    string
	user           string
	namespace      string
	query          string
	expect         []map[string]string
	expectExcludes bool
	expectContains bool
	expectSummary  []clientv1.SteveAPISummaryItem
}

// sqlOnlyListTests are the TestList cases for features only Steve's SQL cache supports: summaries
// and filtering or sorting on metadata.fields.
var sqlOnlyListTests = []listTestType{
	// user-a
	{
		description: "user:user-a,namespace:none,query:summary=metadata.namespace,metadata.name",
		user:        "user-a",
		namespace:   "",
		query:       "summary=metadata.namespace,metadata.name",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-4"},
			{"name": "test2", "namespace": "test-ns-4"},
			{"name": "test3", "namespace": "test-ns-4"},
			{"name": "test4", "namespace": "test-ns-4"},
			{"name": "test5", "namespace": "test-ns-4"},
			{"name": "test1", "namespace": "test-ns-5"},
			{"name": "test2", "namespace": "test-ns-5"},
			{"name": "test3", "namespace": "test-ns-5"},
			{"name": "test4", "namespace": "test-ns-5"},
			{"name": "test5", "namespace": "test-ns-5"},
		},
		expectSummary: []clientv1.SteveAPISummaryItem{
			{
				Property: "metadata.name",
				Counts: map[string]clientv1.SteveSummaryWithBreakdown{
					"test1": {Total: 5},
					"test2": {Total: 5},
					"test3": {Total: 5},
					"test4": {Total: 5},
					"test5": {Total: 5},
				},
			},
			{
				Property: "metadata.namespace",
				Counts: map[string]clientv1.SteveSummaryWithBreakdown{
					"test-ns-1": {Total: 5},
					"test-ns-2": {Total: 5},
					"test-ns-3": {Total: 5},
					"test-ns-4": {Total: 5},
					"test-ns-5": {Total: 5},
				},
			},
		},
	},
	{
		description: "user:user-a,namespace:none,query:pagesize=8&summary=metadata.name,metadata.namespace&sort=metadata.namespace,metadata.name",
		user:        "user-a",
		namespace:   "",
		query:       "pagesize=8&summary=metadata.name,metadata.namespace&sort=metadata.namespace,metadata.name",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
		},
		expectSummary: []clientv1.SteveAPISummaryItem{
			{
				Property: "metadata.name",
				Counts: map[string]clientv1.SteveSummaryWithBreakdown{
					"test1": {Total: 2},
					"test2": {Total: 2},
					"test3": {Total: 2},
					"test4": {Total: 1},
					"test5": {Total: 1},
				},
			},
			{
				Property: "metadata.namespace",
				Counts: map[string]clientv1.SteveSummaryWithBreakdown{
					"test-ns-1": {Total: 5},
					"test-ns-2": {Total: 3},
				},
			},
		},
	},
	{
		description: "user:user-a,namespace:none,query:filter=metadata.labels.test-label-gte=3&sort=-metadata.name&pagesize=6&summary=metadata.name",
		user:        "user-a",
		namespace:   "",
		query:       "filter=metadata.labels.test-label-gte=3&sort=-metadata.name&pagesize=6&summary=metadata.name",
		expect: []map[string]string{
			{"name": "test5"},
			{"name": "test5"},
			{"name": "test5"},
			{"name": "test5"},
			{"name": "test5"},
			{"name": "test4"},
		},
		expectSummary: []clientv1.SteveAPISummaryItem{
			{
				Property: "metadata.name",
				Counts: map[string]clientv1.SteveSummaryWithBreakdown{
					"test4": {Total: 1},
					"test5": {Total: 5},
				},
			},
		},
	},
	{
		description: "user:user-a,namespace:test-ns-2,query:filter=metadata.labels.test-label=2&summary=metadata.namespace,metadata.name",
		user:        "user-a",
		namespace:   "test-ns-2",
		query:       "filter=metadata.labels.test-label=2&summary=metadata.namespace,metadata.name",
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-2"},
		},
		expectSummary: []clientv1.SteveAPISummaryItem{
			{
				Property: "metadata.name",
				Counts: map[string]clientv1.SteveSummaryWithBreakdown{
					"test2": {Total: 1},
				},
			},
			{
				Property: "metadata.namespace",
				Counts: map[string]clientv1.SteveSummaryWithBreakdown{
					"test-ns-2": {Total: 1},
				},
			},
		},
	},
	{
		description: "user:user-a,namespace:none,query:summary=metadata.state.name",
		user:        "user-a",
		namespace:   "none",
		query:       "summary=metadata.state.name",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-4"},
			{"name": "test2", "namespace": "test-ns-4"},
			{"name": "test3", "namespace": "test-ns-4"},
			{"name": "test4", "namespace": "test-ns-4"},
			{"name": "test5", "namespace": "test-ns-4"},
			{"name": "test1", "namespace": "test-ns-5"},
			{"name": "test2", "namespace": "test-ns-5"},
			{"name": "test3", "namespace": "test-ns-5"},
			{"name": "test4", "namespace": "test-ns-5"},
			{"name": "test5", "namespace": "test-ns-5"},
		},
		expectSummary: []clientv1.SteveAPISummaryItem{
			{
				Property: "metadata.state.name",
				Counts: map[string]clientv1.SteveSummaryWithBreakdown{
					"active": {Total: 25},
				},
			},
		},
	},
	{
		// non-sql can't handle annotations and label fields that contain "."s because it splits on them
		description: "user:user-a,namespace:test-ns-2,query:filter=metadata.annotations[management.cattle.io/project-scoped-secret-copy]=spuds",
		user:        "user-a",
		namespace:   "test-ns-2",
		query:       "filter=metadata.annotations[management.cattle.io/project-scoped-secret-copy]=spuds",
		expect: []map[string]string{
			{"name": "test4", "namespace": "test-ns-2"},
		},
	},
	{
		// non-sql doesn't handle the '>' greater-than operator
		description: "user:user-a,namespace:test-ns-1,query:filter=metadata.fields[2]>0&sort=metadata.fields[2]",
		user:        "user-a",
		namespace:   "test-ns-1",
		query:       "filter=metadata.fields[2]>0&sort=metadata.fields[2]",
		expect: []map[string]string{
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
		},
	},
}

// listTests are the TestList cases for filtering, sorting, pagination and project/namespace
// scoping, grouped by user.
var listTests = []listTestType{
	// user-a
	{
		description: "user:user-a,namespace:none,query:none",
		user:        "user-a",
		namespace:   "",
		query:       "",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-4"},
			{"name": "test2", "namespace": "test-ns-4"},
			{"name": "test3", "namespace": "test-ns-4"},
			{"name": "test4", "namespace": "test-ns-4"},
			{"name": "test5", "namespace": "test-ns-4"},
			{"name": "test1", "namespace": "test-ns-5"},
			{"name": "test2", "namespace": "test-ns-5"},
			{"name": "test3", "namespace": "test-ns-5"},
			{"name": "test4", "namespace": "test-ns-5"},
			{"name": "test5", "namespace": "test-ns-5"},
		},
	},
	{
		description: "user:user-a,namespace:none,query:labelSelector=test-label=2",
		user:        "user-a",
		namespace:   "",
		query:       "labelSelector=test-label=2",
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-4"},
			{"name": "test2", "namespace": "test-ns-5"},
		},
	},
	{
		description: "user:user-a,namespace:test-ns-2,query:labelSelector=test-label=2",
		user:        "user-a",
		namespace:   "test-ns-2",
		query:       "labelSelector=test-label=2",
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-2"},
		},
	},
	{
		description: "user:user-a,namespace:test-ns-1,query:none",
		user:        "user-a",
		namespace:   "test-ns-1",
		query:       "",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-a,namespace:test-ns-5,query:none",
		user:        "user-a",
		namespace:   "test-ns-5",
		query:       "",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-5"},
			{"name": "test2", "namespace": "test-ns-5"},
			{"name": "test3", "namespace": "test-ns-5"},
			{"name": "test4", "namespace": "test-ns-5"},
			{"name": "test5", "namespace": "test-ns-5"},
		},
	},
	{
		description: "user:user-a,namespace:none,query:fieldSelector=metadata.namespace=test-ns-1",
		user:        "user-a",
		namespace:   "",
		query:       "fieldSelector=metadata.namespace=test-ns-1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-a,namespace:none,query:fieldSelector=metadata.name=test1",
		user:        "user-a",
		namespace:   "",
		query:       "fieldSelector=metadata.name=test1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-4"},
			{"name": "test1", "namespace": "test-ns-5"},
		},
	},
	{
		description: "user:user-a,namespace:test-ns-1,query:fieldSelector=metadata.namespace=test-ns-1",
		user:        "user-a",
		namespace:   "test-ns-1",
		query:       "fieldSelector=metadata.namespace=test-ns-1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-a,namespace:test-ns-2,query:fieldSelector=metadata.namespace=test-ns-1",
		user:        "user-a",
		namespace:   "test-ns-2",
		query:       "fieldSelector=metadata.namespace=test-ns-1",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-a,namespace:test-ns-1,query:fieldSelector=metadata.name=test1",
		user:        "user-a",
		namespace:   "test-ns-1",
		query:       "fieldSelector=metadata.name=test1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-a,namespace:none,query:filter=metadata.name=test1",
		user:        "user-a",
		namespace:   "",
		query:       "filter=metadata.name=test1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-4"},
			{"name": "test1", "namespace": "test-ns-5"},
		},
	},
	{
		description: "user:user-a,namespace:none,query:filter=metadata.name=test6",
		user:        "user-a",
		namespace:   "",
		query:       "filter=metadata.name=test6",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-a,namespace:test-ns-1,query:filter=metadata.name=test1",
		user:        "user-a",
		namespace:   "test-ns-1",
		query:       "filter=metadata.name=test1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-a,namespace:none,query:filter=metadata.name=test1,metadata.namespace=test-ns-1",
		user:        "user-a",
		namespace:   "",
		query:       "filter=metadata.name=test1,metadata.namespace=test-ns-1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-4"},
			{"name": "test1", "namespace": "test-ns-5"},
		},
	},
	{
		description: "user:user-a,namespace:none,query:filter=metadata.labels.test-label-gte=3,metadata.labels.test-label=2&filter=metadata.namespace=test-ns-1",
		user:        "user-a",
		namespace:   "",
		query:       "filter=metadata.labels.test-label-gte=3,metadata.labels.test-label=2&filter=metadata.namespace=test-ns-1",
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-a,namespace:none,query:filter=metadata.name!=test1",
		user:        "user-a",
		namespace:   "",
		query:       "filter=metadata.name!=test1",
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-4"},
			{"name": "test3", "namespace": "test-ns-4"},
			{"name": "test4", "namespace": "test-ns-4"},
			{"name": "test5", "namespace": "test-ns-4"},
			{"name": "test2", "namespace": "test-ns-5"},
			{"name": "test3", "namespace": "test-ns-5"},
			{"name": "test4", "namespace": "test-ns-5"},
			{"name": "test5", "namespace": "test-ns-5"},
		},
	},
	{
		description: "user:user-a,namespace:test-ns-2,query:filter=metadata.annotations[management.cattle.io/project-scoped-secret-copy]=potatoes",
		user:        "user-a",
		namespace:   "test-ns-2",
		query:       "filter=metadata.annotations[management.cattle.io/project-scoped-secret-copy]=potatoes",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-a,namespace:none,query:sort=metadata.name",
		user:        "user-a",
		namespace:   "",
		query:       "sort=metadata.name",
		expect: []map[string]string{
			{"name": "test1"},
			{"name": "test1"},
			{"name": "test1"},
			{"name": "test1"},
			{"name": "test1"},
			{"name": "test2"},
			{"name": "test2"},
			{"name": "test2"},
			{"name": "test2"},
			{"name": "test2"},
			{"name": "test3"},
			{"name": "test3"},
			{"name": "test3"},
			{"name": "test3"},
			{"name": "test3"},
			{"name": "test4"},
			{"name": "test4"},
			{"name": "test4"},
			{"name": "test4"},
			{"name": "test4"},
			{"name": "test5"},
			{"name": "test5"},
			{"name": "test5"},
			{"name": "test5"},
			{"name": "test5"},
		},
	},
	{
		description: "user:user-a,namespace:none,query:sort=-metadata.name",
		user:        "user-a",
		namespace:   "",
		query:       "sort=-metadata.name",
		expect: []map[string]string{
			{"name": "test5"},
			{"name": "test5"},
			{"name": "test5"},
			{"name": "test5"},
			{"name": "test5"},
			{"name": "test4"},
			{"name": "test4"},
			{"name": "test4"},
			{"name": "test4"},
			{"name": "test4"},
			{"name": "test3"},
			{"name": "test3"},
			{"name": "test3"},
			{"name": "test3"},
			{"name": "test3"},
			{"name": "test2"},
			{"name": "test2"},
			{"name": "test2"},
			{"name": "test2"},
			{"name": "test2"},
			{"name": "test1"},
			{"name": "test1"},
			{"name": "test1"},
			{"name": "test1"},
			{"name": "test1"},
		},
	},
	{
		description: "user:user-a,namespace:none,query:sort=metadata.name,metadata.namespace",
		user:        "user-a",
		namespace:   "",
		query:       "sort=metadata.name,metadata.namespace",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-4"},
			{"name": "test1", "namespace": "test-ns-5"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-4"},
			{"name": "test2", "namespace": "test-ns-5"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-4"},
			{"name": "test3", "namespace": "test-ns-5"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-4"},
			{"name": "test4", "namespace": "test-ns-5"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-4"},
			{"name": "test5", "namespace": "test-ns-5"},
		},
	},
	{
		description: "user:user-a,namespace:none,query:sort=metadata.name,-metadata.namespace",
		user:        "user-a",
		namespace:   "",
		query:       "sort=metadata.name,-metadata.namespace",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-5"},
			{"name": "test1", "namespace": "test-ns-4"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-5"},
			{"name": "test2", "namespace": "test-ns-4"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-5"},
			{"name": "test3", "namespace": "test-ns-4"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-5"},
			{"name": "test4", "namespace": "test-ns-4"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-5"},
			{"name": "test5", "namespace": "test-ns-4"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-a,namespace:test-ns-1,query:sort=metadata.name",
		user:        "user-a",
		namespace:   "test-ns-1",
		query:       "sort=metadata.name",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-a,namespace:test-ns-1,query:sort=-metadata.name",
		user:        "user-a",
		namespace:   "test-ns-1",
		query:       "sort=-metadata.name",
		expect: []map[string]string{
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-a,namespace:none,query:pagesize=8",
		user:        "user-a",
		namespace:   "",
		query:       "pagesize=8",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
		},
	},
	{
		description: "user:user-a,namespace:none,query:pagesize=8&page=2&revision=" + revisionNum,
		user:        "user-a",
		namespace:   "",
		query:       "pagesize=8&page=2&revision=" + revisionNum,
		expect: []map[string]string{
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-4"},
		},
	},
	{
		description: "user:user-a,namespace:test-ns-1,query:pagesize=3",
		user:        "user-a",
		namespace:   "test-ns-1",
		query:       "pagesize=3",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-a,namespace:test-ns-1,query:pagesize=3&page=2&revision=" + revisionNum,
		user:        "user-a",
		namespace:   "test-ns-1",
		query:       "pagesize=3&page=2&revision=" + revisionNum,
		expect: []map[string]string{
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},

	// user-b
	{
		description: "user:user-b,namespace:none,query:none",
		user:        "user-b",
		namespace:   "",
		query:       "",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:test-ns-1,query:none",
		user:        "user-b",
		namespace:   "test-ns-1",
		query:       "",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:test-ns-5,query:none",
		user:        "user-b",
		namespace:   "test-ns-5",
		query:       "",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-b,namespace:none,query:labelSelector=test-label=2",
		user:        "user-b",
		namespace:   "",
		query:       "labelSelector=test-label=2",
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:test-ns-1,query:labelSelector=test-label=2",
		user:        "user-b",
		namespace:   "test-ns-1",
		query:       "labelSelector=test-label=2",
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:test-ns-2,query:labelSelector=test-label=2",
		user:        "user-b",
		namespace:   "test-ns-2",
		query:       "labelSelector=test-label=2",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-b,namespace:none,query:fieldSelector=metadata.namespace=test-ns-1",
		user:        "user-b",
		namespace:   "",
		query:       "fieldSelector=metadata.namespace=test-ns-1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:none,query:fieldSelector=metadata.namespace=test-ns-2",
		user:        "user-b",
		namespace:   "",
		query:       "fieldSelector=metadata.namespace=test-ns-2",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-b,namespace:none,query:fieldSelector=metadata.name=test1",
		user:        "user-b",
		namespace:   "",
		query:       "fieldSelector=metadata.name=test1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:test-ns-1,query:fieldSelector=metadata.namespace=test-ns-1",
		user:        "user-b",
		namespace:   "test-ns-1",
		query:       "fieldSelector=metadata.namespace=test-ns-1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:test-ns-2,query:fieldSelector=metadata.namespace=test-ns-1",
		user:        "user-b",
		namespace:   "test-ns-2",
		query:       "fieldSelector=metadata.namespace=test-ns-1",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-b,namespace:test-ns-1,query:fieldSelector=metadata.namespace=test-ns-2",
		user:        "user-b",
		namespace:   "test-ns-1",
		query:       "fieldSelector=metadata.namespace=test-ns-2",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-b,namespace:test-ns-1,query:fieldSelector=metadata.name=test1",
		user:        "user-b",
		namespace:   "test-ns-1",
		query:       "fieldSelector=metadata.name=test1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:test-ns-2,query:fieldSelector=metadata.name=test1",
		user:        "user-b",
		namespace:   "test-ns-2",
		query:       "fieldSelector=metadata.name=test1",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-b,namespace:none,query:filter=metadata.name=test1",
		user:        "user-b",
		namespace:   "",
		query:       "filter=metadata.name=test1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:test-ns-1,query:filter=metadata.name=test1",
		user:        "user-b",
		namespace:   "test-ns-1",
		query:       "filter=metadata.name=test1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:test-ns-1,query:filter=metadata.name=test6",
		user:        "user-b",
		namespace:   "test-ns-1",
		query:       "filter=metadata.name=test6",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-b,namespace:none,query:filter=metadata.name=test1,metadata.namespace=test-ns-1",
		user:        "user-b",
		namespace:   "",
		query:       "filter=metadata.name=test1,metadata.namespace=test-ns-1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:none,query:filter=metadata.labels.test-label-gte=3,metadata.labels.test-label=2&filter=metadata.namespace=test-ns-1",
		user:        "user-b",
		namespace:   "",
		query:       "filter=metadata.labels.test-label-gte=3,metadata.labels.test-label=2&filter=metadata.namespace=test-ns-1",
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:none,query:filter=metadata.name!=test1",
		user:        "user-b",
		namespace:   "",
		query:       "filter=metadata.name!=test1",
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:none,query:sort=metadata.name",
		user:        "user-b",
		namespace:   "",
		query:       "sort=metadata.name",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:none,query:sort=-metadata.name",
		user:        "user-b",
		namespace:   "",
		query:       "sort=-metadata.name",
		expect: []map[string]string{
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:none,query:sort=metadata.name,metadata.namespace",
		user:        "user-b",
		namespace:   "",
		query:       "sort=metadata.name,metadata.namespace",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:none,query:sort=-metadata.name,metadata.namespace",
		user:        "user-b",
		namespace:   "",
		query:       "sort=-metadata.name,metadata.namespace",
		expect: []map[string]string{
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:test-ns-1,query:sort=metadata.name",
		user:        "user-b",
		namespace:   "test-ns-1",
		query:       "sort=metadata.name",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:test-ns-1,query:sort=-metadata.name",
		user:        "user-b",
		namespace:   "test-ns-1",
		query:       "sort=-metadata.name",
		expect: []map[string]string{
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:test-ns-5,query:sort=metadata.name",
		user:        "user-b",
		namespace:   "test-ns-5",
		query:       "sort=metadata.name",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-b,namespace:none,query:pagesize=3",
		user:        "user-b",
		namespace:   "",
		query:       "pagesize=3",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:none,query:pagesize=3&page=2&revision=" + revisionNum,
		user:        "user-b",
		namespace:   "",
		query:       "pagesize=3&page=2&revision=" + revisionNum,
		expect: []map[string]string{
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:test-ns-1,query:pagesize=3",
		user:        "user-b",
		namespace:   "test-ns-1",
		query:       "pagesize=3",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:test-ns-1,query:pagesize=3&page=2&revision=" + revisionNum,
		user:        "user-b",
		namespace:   "test-ns-1",
		query:       "pagesize=3&page=2&revision=" + revisionNum,
		expect: []map[string]string{
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:test-ns-5,query:pagesize=3",
		user:        "user-b",
		namespace:   "test-ns-5",
		query:       "pagesize=3",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-b,namespace:none,query:filter=metadata.labels.test-label-gte=3&sort=-metadata.name&pagesize=2",
		user:        "user-b",
		namespace:   "",
		query:       "filter=metadata.labels.test-label-gte=3&sort=-metadata.name&pagesize=2",
		expect: []map[string]string{
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-b,namespace:none,query:filter=metadata.labels.test-label-gte=3&sort=-metadata.name&pagesize=2&page=2&revision=" + revisionNum,
		user:        "user-b",
		namespace:   "",
		query:       "filter=metadata.labels.test-label-gte=3&sort=-metadata.name&pagesize=2&page=2&revision=" + revisionNum,
		expect: []map[string]string{
			{"name": "test3", "namespace": "test-ns-1"},
		},
	},

	// user-c
	{
		description: "user:user-c,namespace:none,query:none",
		user:        "user-c",
		namespace:   "",
		query:       "",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-3"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-1,query:none",
		user:        "user-c",
		namespace:   "test-ns-1",
		query:       "",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-5,query:none",
		user:        "user-c",
		namespace:   "test-ns-5",
		query:       "",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-c,namespace:none,query:labelSelector=test-label=2",
		user:        "user-c",
		namespace:   "",
		query:       "labelSelector=test-label=2",
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-3"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-1,query:labelSelector=test-label=2",
		user:        "user-c",
		namespace:   "test-ns-1",
		query:       "labelSelector=test-label=2",
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-5,query:labelSelector=test-label=2",
		user:        "user-c",
		namespace:   "test-ns-5",
		query:       "labelSelector=test-label=2",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-c,namespace:none,query:fieldSelector=metadata.namespace=test-ns-1",
		user:        "user-c",
		namespace:   "",
		query:       "fieldSelector=metadata.namespace=test-ns-1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-c,namespace:none,query:fieldSelector=metadata.namespace=test-ns-2",
		user:        "user-c",
		namespace:   "",
		query:       "fieldSelector=metadata.namespace=test-ns-2",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
		},
	},
	{
		description: "user:user-c,namespace:none,query:fieldSelector=metadata.namespace=test-ns-5",
		user:        "user-c",
		namespace:   "",
		query:       "fieldSelector=metadata.namespace=test-ns-5",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-c,namespace:none,query:fieldSelector=metadata.name=test1",
		user:        "user-c",
		namespace:   "",
		query:       "fieldSelector=metadata.name=test1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
		},
	},
	{
		description: "user:user-c,namespace:none,query:fieldSelector=metadata.name=test5",
		user:        "user-c",
		namespace:   "",
		query:       "fieldSelector=metadata.name=test5",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-c,namespace:test-ns-1,query:fieldSelector=metadata.namespace=test-ns-1",
		user:        "user-c",
		namespace:   "test-ns-1",
		query:       "fieldSelector=metadata.namespace=test-ns-1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-2,query:fieldSelector=metadata.namespace=test-ns-1",
		user:        "user-c",
		namespace:   "test-ns-2",
		query:       "fieldSelector=metadata.namespace=test-ns-1",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-c,namespace:test-ns-1,query:fieldSelector=metadata.namespace=test-ns-2",
		user:        "user-c",
		namespace:   "test-ns-1",
		query:       "fieldSelector=metadata.namespace=test-ns-2",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-c,namespace:test-ns-1,query:fieldSelector=metadata.name=test1",
		user:        "user-c",
		namespace:   "test-ns-1",
		query:       "fieldSelector=metadata.name=test1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-5,query:fieldSelector=metadata.name=test1",
		user:        "user-c",
		namespace:   "test-ns-5",
		query:       "fieldSelector=metadata.name=test1",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-c,namespace:test-ns-1,query:fieldSelector=metadata.name=test5",
		user:        "user-c",
		namespace:   "test-ns-1",
		query:       "fieldSelector=metadata.name=test5",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-c,namespace:none,query:filter=metadata.name=test1",
		user:        "user-c",
		namespace:   "",
		query:       "filter=metadata.name=test1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-1,query:filter=metadata.name=test1",
		user:        "user-c",
		namespace:   "test-ns-1",
		query:       "filter=metadata.name=test1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-1,query:filter=metadata.name=test3",
		user:        "user-c",
		namespace:   "test-ns-1",
		query:       "filter=metadata.name=test3",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-c,namespace:none,query:filter=metadata.name=test1,metadata.namespace=test-ns-1",
		user:        "user-c",
		namespace:   "",
		query:       "filter=metadata.name=test1,metadata.namespace=test-ns-1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-1,query:filter=metadata.name!=test1",
		user:        "user-c",
		namespace:   "",
		query:       "filter=metadata.name!=test1",
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-3"},
		},
	},
	{
		description: "user:user-c,namespace:none,query:filter=metadata.labels.test-label-gte=3,metadata.labels.test-label=2&filter=metadata.namespace=test-ns-1",
		user:        "user-c",
		namespace:   "",
		query:       "filter=metadata.labels.test-label-gte=3,metadata.labels.test-label=2&filter=metadata.namespace=test-ns-1",
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-c,namespace:none,query:sort=metadata.name",
		user:        "user-c",
		namespace:   "",
		query:       "sort=metadata.name",
		expect: []map[string]string{
			{"name": "test1"},
			{"name": "test1"},
			{"name": "test1"},
			{"name": "test2"},
			{"name": "test2"},
			{"name": "test2"},
		},
	},
	{
		description: "user:user-c,namespace:none,query:sort=-metadata.name",
		user:        "user-c",
		namespace:   "",
		query:       "sort=-metadata.name",
		expect: []map[string]string{
			{"name": "test2"},
			{"name": "test2"},
			{"name": "test2"},
			{"name": "test1"},
			{"name": "test1"},
			{"name": "test1"},
		},
	},
	{
		description: "user:user-c,namespace:none,query:sort=metadata.name,metadata.namespace",
		user:        "user-c",
		namespace:   "",
		query:       "sort=metadata.name,metadata.namespace",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-3"},
		},
	},
	{
		description: "user:user-c,namespace:none,query:sort=metadata.name,-metadata.namespace",
		user:        "user-c",
		namespace:   "",
		query:       "sort=metadata.name,-metadata.namespace",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-1,query:sort=metadata.name",
		user:        "user-c",
		namespace:   "test-ns-1",
		query:       "sort=metadata.name",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-1,query:sort=-metadata.name",
		user:        "user-c",
		namespace:   "test-ns-1",
		query:       "sort=-metadata.name",
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-1,query:sort=metadata.name,metadata.namespace",
		user:        "user-c",
		namespace:   "test-ns-1",
		query:       "sort=metadata.name,metadata.namespace",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-1,query:sort=metadata.name,-metadata.namespace",
		user:        "user-c",
		namespace:   "test-ns-1",
		query:       "sort=metadata.name,-metadata.namespace",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-5,query:sort=metadata.name",
		user:        "user-c",
		namespace:   "test-ns-5",
		query:       "sort=metadata.name",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-c,namespace:none,query:pagesize=3",
		user:        "user-c",
		namespace:   "",
		query:       "pagesize=3",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
		},
	},
	{
		description: "user:user-c,namespace:none,query:pagesize=3&page=2&revision=" + revisionNum,
		user:        "user-c",
		namespace:   "",
		query:       "pagesize=3&page=2&revision=" + revisionNum,
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-3"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-1,query:pagesize=3",
		user:        "user-c",
		namespace:   "test-ns-1",
		query:       "pagesize=3",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-c,namespace:test-ns-5,query:pagesize=3",
		user:        "user-c",
		namespace:   "test-ns-5",
		query:       "pagesize=3",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-c,namespace:none,query:filter=metadata.namespace=test-ns-3&sort=-metadata.name&pagesize=1",
		user:        "user-c",
		namespace:   "",
		query:       "filter=metadata.namespace=test-ns-3&sort=-metadata.name&pagesize=1",
		expect: []map[string]string{
			{"name": "test2", "namespace": "test-ns-3"},
		},
	},
	{
		description: "user:user-c,namespace:none,query:filter=metadata.namespace=test-ns-3&sort=-metadata.name&pagesize=1&page=2&revision=" + revisionNum,
		user:        "user-c",
		namespace:   "",
		query:       "filter=metadata.namespace=test-ns-3&sort=-metadata.name&pagesize=1&page=2&revision=" + revisionNum,
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-3"},
		},
	},

	// user-d
	{
		description: "user:user-d,namespace:none,query:none",
		user:        "user-d",
		query:       "",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-4"},
			{"name": "test2", "namespace": "test-ns-4"},
			{"name": "test3", "namespace": "test-ns-4"},
			{"name": "test4", "namespace": "test-ns-4"},
			{"name": "test5", "namespace": "test-ns-4"},
			{"name": "test1", "namespace": "test-ns-5"},
			{"name": "test2", "namespace": "test-ns-5"},
			{"name": "test3", "namespace": "test-ns-5"},
			{"name": "test4", "namespace": "test-ns-5"},
			{"name": "test5", "namespace": "test-ns-5"},
			{"name": "test1", "namespace": "test-ns-6"},
			{"name": "test2", "namespace": "test-ns-6"},
			{"name": "test1", "namespace": "test-ns-7"},
			{"name": "test2", "namespace": "test-ns-7"},
			{"name": "test1", "namespace": "test-ns-8"},
			{"name": "test2", "namespace": "test-ns-8"},
			{"name": "test1", "namespace": "test-ns-9"},
			{"name": "test2", "namespace": "test-ns-9"},
		},
	},
	{
		description: "user:user-d,namespace:none,query:projectsornamespaces=test-prj-2",
		user:        "user-d",
		query:       "projectsornamespaces=test-prj-2",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-6"},
			{"name": "test2", "namespace": "test-ns-6"},
			{"name": "test1", "namespace": "test-ns-7"},
			{"name": "test2", "namespace": "test-ns-7"},
		},
	},
	{
		description: "user:user-d,namespace:none,query:projectsornamespaces=test-prj-1,test-prj-2",
		user:        "user-d",
		query:       "projectsornamespaces=test-prj-1,test-prj-2",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-4"},
			{"name": "test2", "namespace": "test-ns-4"},
			{"name": "test3", "namespace": "test-ns-4"},
			{"name": "test4", "namespace": "test-ns-4"},
			{"name": "test5", "namespace": "test-ns-4"},
			{"name": "test1", "namespace": "test-ns-5"},
			{"name": "test2", "namespace": "test-ns-5"},
			{"name": "test3", "namespace": "test-ns-5"},
			{"name": "test4", "namespace": "test-ns-5"},
			{"name": "test5", "namespace": "test-ns-5"},
			{"name": "test1", "namespace": "test-ns-6"},
			{"name": "test2", "namespace": "test-ns-6"},
			{"name": "test1", "namespace": "test-ns-7"},
			{"name": "test2", "namespace": "test-ns-7"},
		},
	},
	{
		description: "user:user-d,namespace:none,query:projectsornamespaces=test-ns-1",
		user:        "user-d",
		query:       "projectsornamespaces=test-ns-1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-d,namespace:none,query:projectsornamespaces=test-ns-1,test-ns-2",
		user:        "user-d",
		query:       "projectsornamespaces=test-ns-1,test-ns-2",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
		},
	},
	{
		description: "user:user-d,namespace:none,query:projectsornamespaces=test-prj-2,test-ns-2,test-ns-3",
		user:        "user-d",
		query:       "projectsornamespaces=test-prj-2,test-ns-2,test-ns-3",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-6"},
			{"name": "test2", "namespace": "test-ns-6"},
			{"name": "test1", "namespace": "test-ns-7"},
			{"name": "test2", "namespace": "test-ns-7"},
		},
	},
	{
		description: "user:user-d,namespace:none,query:projectsornamespaces=test-ns-8,test-ns-9",
		user:        "user-d",
		query:       "projectsornamespaces=test-ns-8,test-ns-9",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-8"},
			{"name": "test2", "namespace": "test-ns-8"},
			{"name": "test1", "namespace": "test-ns-9"},
			{"name": "test2", "namespace": "test-ns-9"},
		},
	},
	{
		description: "user:user-d,namespace:none,query:projectsornamespaces!=test-prj-1",
		user:        "user-d",
		query:       "projectsornamespaces!=test-prj-1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-6"},
			{"name": "test2", "namespace": "test-ns-6"},
			{"name": "test1", "namespace": "test-ns-7"},
			{"name": "test2", "namespace": "test-ns-7"},
			{"name": "test1", "namespace": "test-ns-8"},
			{"name": "test2", "namespace": "test-ns-8"},
			{"name": "test1", "namespace": "test-ns-9"},
			{"name": "test2", "namespace": "test-ns-9"},
		},
	},
	{
		description: "user:user-d,namespace:none,query:projectsornamespaces!=test-prj-1,test-prj-2",
		user:        "user-d",
		query:       "projectsornamespaces!=test-prj-1,test-prj-2",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-8"},
			{"name": "test2", "namespace": "test-ns-8"},
			{"name": "test1", "namespace": "test-ns-9"},
			{"name": "test2", "namespace": "test-ns-9"},
		},
	},
	{
		description: "user:user-d,namespace:none,query:projectsornamespaces!=test-prj-1,test-ns-6,test-ns-8",
		user:        "user-d",
		query:       "projectsornamespaces!=test-prj-1,test-ns-6,test-ns-8",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-7"},
			{"name": "test2", "namespace": "test-ns-7"},
			{"name": "test1", "namespace": "test-ns-9"},
			{"name": "test2", "namespace": "test-ns-9"},
		},
	},
	{
		description: "user:user-d,namespace:test-ns-6,query:none",
		user:        "user-d",
		namespace:   "test-ns-6",
		query:       "",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-6"},
			{"name": "test2", "namespace": "test-ns-6"},
		},
	},
	{
		description: "user:user-d,namespace:test-ns-6,query:projectsornamespaces=test-prj-2",
		user:        "user-d",
		namespace:   "test-ns-6",
		query:       "projectsornamespaces=test-prj-2",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-6"},
			{"name": "test2", "namespace": "test-ns-6"},
		},
	},
	{
		description: "user:user-d,namespace:test-ns-6,query:projectsornamespaces=test-prj-2",
		user:        "user-d",
		namespace:   "test-ns-6",
		query:       "projectsornamespaces=test-prj-1",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-d,namespace:test-ns-1,query:projectsornamespaces=test-ns-1,test-ns-2,-test-prj-2,test-ns-7",
		user:        "user-d",
		namespace:   "test-ns-1",
		query:       "projectsornamespaces=test-ns-1,test-ns-2,test-prj-2,test-ns-7",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-d,namespace:test-ns-1,query:projectsornamespaces!=test-prj-1",
		user:        "user-d",
		namespace:   "test-ns-1",
		query:       "projectsornamespaces!=test-prj-1",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-d,namespace:test-ns-1,query:projectsornamespaces!=test-prj-1,test-prj-2",
		user:        "user-d",
		namespace:   "test-ns-1",
		query:       "projectsornamespaces!=test-prj-1,test-prj-2",
		expect:      []map[string]string{},
	},

	// user-e
	{
		description: "user:user-e,namespace:none,query:none",
		user:        "user-e",
		query:       "",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-4"},
			{"name": "test2", "namespace": "test-ns-4"},
			{"name": "test3", "namespace": "test-ns-4"},
			{"name": "test4", "namespace": "test-ns-4"},
			{"name": "test5", "namespace": "test-ns-4"},
			{"name": "test1", "namespace": "test-ns-5"},
			{"name": "test2", "namespace": "test-ns-5"},
			{"name": "test3", "namespace": "test-ns-5"},
			{"name": "test4", "namespace": "test-ns-5"},
			{"name": "test5", "namespace": "test-ns-5"},
			{"name": "test1", "namespace": "test-ns-6"},
			{"name": "test2", "namespace": "test-ns-6"},
			{"name": "test1", "namespace": "test-ns-7"},
			{"name": "test2", "namespace": "test-ns-7"},
			{"name": "test1", "namespace": "test-ns-8"},
			{"name": "test2", "namespace": "test-ns-8"},
			{"name": "test1", "namespace": "test-ns-9"},
			{"name": "test2", "namespace": "test-ns-9"},
		},
		expectContains: true,
	},
	{
		description: "user:user-e,namespace:none,query:projectsornamespaces=test-prj-2",
		user:        "user-e",
		query:       "projectsornamespaces=test-prj-2",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-6"},
			{"name": "test2", "namespace": "test-ns-6"},
			{"name": "test1", "namespace": "test-ns-7"},
			{"name": "test2", "namespace": "test-ns-7"},
		},
	},
	{
		description: "user:user-e,namespace:none,query:projectsornamespaces=test-prj-1,test-prj-2",
		user:        "user-e",
		query:       "projectsornamespaces=test-prj-1,test-prj-2",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-4"},
			{"name": "test2", "namespace": "test-ns-4"},
			{"name": "test3", "namespace": "test-ns-4"},
			{"name": "test4", "namespace": "test-ns-4"},
			{"name": "test5", "namespace": "test-ns-4"},
			{"name": "test1", "namespace": "test-ns-5"},
			{"name": "test2", "namespace": "test-ns-5"},
			{"name": "test3", "namespace": "test-ns-5"},
			{"name": "test4", "namespace": "test-ns-5"},
			{"name": "test5", "namespace": "test-ns-5"},
			{"name": "test1", "namespace": "test-ns-6"},
			{"name": "test2", "namespace": "test-ns-6"},
			{"name": "test1", "namespace": "test-ns-7"},
			{"name": "test2", "namespace": "test-ns-7"},
		},
	},
	{
		description: "user:user-e,namespace:none,query:projectsornamespaces=test-ns-1",
		user:        "user-e",
		query:       "projectsornamespaces=test-ns-1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-e,namespace:none,query:projectsornamespaces=test-ns-1,test-ns-2",
		user:        "user-e",
		query:       "projectsornamespaces=test-ns-1,test-ns-2",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
		},
	},
	{
		description: "user:user-e,namespace:none,query:projectsornamespaces=test-prj-2,test-ns-2,test-ns-3",
		user:        "user-e",
		query:       "projectsornamespaces=test-prj-2,test-ns-2,test-ns-3",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-6"},
			{"name": "test2", "namespace": "test-ns-6"},
			{"name": "test1", "namespace": "test-ns-7"},
			{"name": "test2", "namespace": "test-ns-7"},
		},
	},
	{
		description: "user:user-e,namespace:none,query:projectsornamespaces=test-ns-8,test-ns-9",
		user:        "user-e",
		query:       "projectsornamespaces=test-ns-8,test-ns-9",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-8"},
			{"name": "test2", "namespace": "test-ns-8"},
			{"name": "test1", "namespace": "test-ns-9"},
			{"name": "test2", "namespace": "test-ns-9"},
		},
	},
	{
		description: "user:user-e,namespace:none,query:projectsornamespaces!=test-prj-1",
		user:        "user-e",
		query:       "projectsornamespaces!=test-prj-1",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-4"},
			{"name": "test2", "namespace": "test-ns-4"},
			{"name": "test3", "namespace": "test-ns-4"},
			{"name": "test4", "namespace": "test-ns-4"},
			{"name": "test5", "namespace": "test-ns-4"},
			{"name": "test1", "namespace": "test-ns-5"},
			{"name": "test2", "namespace": "test-ns-5"},
			{"name": "test3", "namespace": "test-ns-5"},
			{"name": "test4", "namespace": "test-ns-5"},
			{"name": "test5", "namespace": "test-ns-5"},
		},
		expectExcludes: true,
	},
	{
		description: "user:user-e,namespace:none,query:projectsornamespaces!=test-prj-1,test-prj-2",
		user:        "user-e",
		query:       "projectsornamespaces!=test-prj-1,test-prj-2",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-4"},
			{"name": "test2", "namespace": "test-ns-4"},
			{"name": "test3", "namespace": "test-ns-4"},
			{"name": "test4", "namespace": "test-ns-4"},
			{"name": "test5", "namespace": "test-ns-4"},
			{"name": "test1", "namespace": "test-ns-5"},
			{"name": "test2", "namespace": "test-ns-5"},
			{"name": "test3", "namespace": "test-ns-5"},
			{"name": "test4", "namespace": "test-ns-5"},
			{"name": "test5", "namespace": "test-ns-5"},
			{"name": "test1", "namespace": "test-ns-6"},
			{"name": "test2", "namespace": "test-ns-6"},
			{"name": "test1", "namespace": "test-ns-7"},
			{"name": "test2", "namespace": "test-ns-7"},
		},
		expectExcludes: true,
	},
	{
		description: "user:user-e,namespace:none,query:projectsornamespaces!=test-prj-1,test-ns-6,test-ns-8",
		user:        "user-e",
		query:       "projectsornamespaces!=test-prj-1,test-ns-6,test-ns-8",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
			{"name": "test1", "namespace": "test-ns-2"},
			{"name": "test2", "namespace": "test-ns-2"},
			{"name": "test3", "namespace": "test-ns-2"},
			{"name": "test4", "namespace": "test-ns-2"},
			{"name": "test5", "namespace": "test-ns-2"},
			{"name": "test1", "namespace": "test-ns-3"},
			{"name": "test2", "namespace": "test-ns-3"},
			{"name": "test3", "namespace": "test-ns-3"},
			{"name": "test4", "namespace": "test-ns-3"},
			{"name": "test5", "namespace": "test-ns-3"},
			{"name": "test1", "namespace": "test-ns-4"},
			{"name": "test2", "namespace": "test-ns-4"},
			{"name": "test3", "namespace": "test-ns-4"},
			{"name": "test4", "namespace": "test-ns-4"},
			{"name": "test5", "namespace": "test-ns-4"},
			{"name": "test1", "namespace": "test-ns-5"},
			{"name": "test2", "namespace": "test-ns-5"},
			{"name": "test3", "namespace": "test-ns-5"},
			{"name": "test4", "namespace": "test-ns-5"},
			{"name": "test5", "namespace": "test-ns-5"},
			{"name": "test1", "namespace": "test-ns-6"},
			{"name": "test2", "namespace": "test-ns-6"},
			{"name": "test1", "namespace": "test-ns-8"},
			{"name": "test2", "namespace": "test-ns-8"},
		},
		expectExcludes: true,
	},
	{
		description: "user:user-e,namespace:test-ns-6,query:none",
		user:        "user-e",
		namespace:   "test-ns-6",
		query:       "",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-6"},
			{"name": "test2", "namespace": "test-ns-6"},
		},
	},
	{
		description: "user:user-e,namespace:test-ns-6,query:projectsornamespaces=test-prj-2",
		user:        "user-e",
		namespace:   "test-ns-6",
		query:       "projectsornamespaces=test-prj-2",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-6"},
			{"name": "test2", "namespace": "test-ns-6"},
		},
	},
	{
		description: "user:user-e,namespace:test-ns-6,query:projectsornamespaces=test-prj-1",
		user:        "user-e",
		namespace:   "test-ns-6",
		query:       "projectsornamespaces=test-prj-1",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-e,namespace:test-ns-1,query:projectsornamespaces=test-ns-1,test-ns-2,test-prj-2,test-ns-7",
		user:        "user-e",
		namespace:   "test-ns-1",
		query:       "projectsornamespaces=test-ns-1,test-ns-2,test-prj-2,test-ns-7",
		expect: []map[string]string{
			{"name": "test1", "namespace": "test-ns-1"},
			{"name": "test2", "namespace": "test-ns-1"},
			{"name": "test3", "namespace": "test-ns-1"},
			{"name": "test4", "namespace": "test-ns-1"},
			{"name": "test5", "namespace": "test-ns-1"},
		},
	},
	{
		description: "user:user-e,namespace:test-ns-1,query:projectsornamespaces!=test-prj-1",
		user:        "user-e",
		namespace:   "test-ns-1",
		query:       "projectsornamespaces!=test-prj-1",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-e,namespace:test-ns-1,query:projectsornamespaces!=test-prj-1,test-prj-2",
		user:        "user-e",
		namespace:   "test-ns-1",
		query:       "projectsornamespaces!=test-prj-1,test-prj-2",
		expect:      []map[string]string{},
	},
	{
		description: "user:user-e,namespace:test-ns-1,query:projectsornamespaces!=test-prj-1,test-ns-2,test-ns-8",
		user:        "user-e",
		namespace:   "test-ns-1",
		query:       "projectsornamespaces!=test-prj-1,test-ns-2,test-ns-8",
		expect:      []map[string]string{},
	},
}
